saurabh - fix issue regarding to start agent on fedora machine

diff --git a/scripts/agent_controller b/scripts/agent_controller
--- a/scripts/agent_controller
+++ b/scripts/agent_controller
@@ -15,19 +15,38 @@
 
 start() {
 
-    echo ""
+    echo "Going to execute start function"
     echo $"***********  agent_controller service started. Triggered from /etc/init.d/agent_controller.service ***********"
 
     command="/opt/infraguard/sbin/infraGuardMain"
-    daemon "nohup $command >/dev/null 2>&1 &"
+    # daemon "nohup $command >/dev/null 2>&1 &"
+    $command >/dev/null 2>&1 &
+    echo "End of start function : $?"
 }
 
-
+# To execute this from CLI --> /etc/init.d/agent_controller.service stop
 stop(){
-    echo "Going to kill process agent_controller.service"
-    pkill  agent_controller.service
+echo "Going to kill process agent_controller.service"
+pkill  agent_controller.service
+
+
+pId=$(ps -ef | grep 'infraGuardMain' | grep -v 'grep' | awk '{ printf $2 }')
+echo "pId = : $pId"
+command="/bin/kill -9 $pId"
+$command
+
+
+
+if [ $? != 0 ]; then                   
+   echo "Unable to kill process id $pId" 
+else
+   command="chkconfig --del agent_controller.service"
+   $command 
+   echo "Process $pId killed successfully " 
+fi
 
 }
+
 
 
 case "$1" in
